// <auto-generated />
using System;
using Bookshelf.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Bookshelf.DataAccess.Migrations
{
    [DbContext(typeof(BookshelfContext))]
    [Migration("20260420181301_Add_Books")]
    partial class Add_Books
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Bookshelf.DataModel.Author", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_author");

                    b.ToTable("authors", (string)null);
                });

            modelBuilder.Entity("Bookshelf.DataModel.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("external_id");

                    b.Property<string>("Isbn")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("isbn");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("language");

                    b.Property<int>("Pages")
                        .HasColumnType("integer")
                        .HasColumnName("pages");

                    b.Property<DateTime>("PublishDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("publish_date");

                    b.Property<Guid?>("PublisherId")
                        .HasColumnType("uuid")
                        .HasColumnName("publisher_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.HasKey("Id")
                        .HasName("pk_book");

                    b.HasIndex("PublisherId");

                    b.ToTable("books", (string)null);
                });

            modelBuilder.Entity("Bookshelf.DataModel.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_category");

                    b.ToTable("categories", (string)null);
                });

            modelBuilder.Entity("Bookshelf.DataModel.Publisher", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_publisher");

                    b.ToTable("publishers", (string)null);
                });

            modelBuilder.Entity("Bookshelf.DataModel.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ExternalReference")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("external_reference");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_user");

                    b.HasIndex(new[] { "Username" }, "ix_username")
                        .IsUnique();

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("Bookshelf.DataModel.UserBookRelation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BookId")
                        .HasColumnType("uuid")
                        .HasColumnName("book_id");

                    b.Property<int>("Count")
                        .HasColumnType("integer")
                        .HasColumnName("count");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_book_relation");

                    b.HasIndex("BookId");

                    b.HasIndex("UserId");

                    b.ToTable("user_book_relations", (string)null);
                });

            modelBuilder.Entity("book_author_relation", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("author")
                        .HasColumnType("uuid")
                        .HasColumnName("author");

                    b.Property<Guid>("book")
                        .HasColumnType("uuid")
                        .HasColumnName("book");

                    b.HasKey("id")
                        .HasName("pk_book_author_relation");

                    b.HasIndex(new[] { "author" }, "ix_book_author_relation_author");

                    b.HasIndex(new[] { "book" }, "ix_book_author_relation_book");

                    b.ToTable("book_author_relation");
                });

            modelBuilder.Entity("book_category_relation", b =>
                {
                    b.Property<Guid>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("book")
                        .HasColumnType("uuid")
                        .HasColumnName("book");

                    b.Property<Guid>("category")
                        .HasColumnType("uuid")
                        .HasColumnName("category");

                    b.HasKey("id")
                        .HasName("pk_book_category_relation");

                    b.HasIndex(new[] { "book" }, "ix_book_category_relation_book");

                    b.HasIndex(new[] { "category" }, "ix_book_category_relation_category");

                    b.ToTable("book_category_relation");
                });

            modelBuilder.Entity("Bookshelf.DataModel.Book", b =>
                {
                    b.HasOne("Bookshelf.DataModel.Publisher", "Publisher")
                        .WithMany("Books")
                        .HasForeignKey("PublisherId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_book_publisher");

                    b.Navigation("Publisher");
                });

            modelBuilder.Entity("Bookshelf.DataModel.UserBookRelation", b =>
                {
                    b.HasOne("Bookshelf.DataModel.Book", "Book")
                        .WithMany("UserBookRelations")
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_book_relation_book");

                    b.HasOne("Bookshelf.DataModel.User", "User")
                        .WithMany("UserBookRelations")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_book_relation_user");

                    b.Navigation("Book");

                    b.Navigation("User");
                });

            modelBuilder.Entity("book_author_relation", b =>
                {
                    b.HasOne("Bookshelf.DataModel.Author", null)
                        .WithMany()
                        .HasForeignKey("author")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_book_author");

                    b.HasOne("Bookshelf.DataModel.Book", null)
                        .WithMany()
                        .HasForeignKey("book")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_author_book");
                });

            modelBuilder.Entity("book_category_relation", b =>
                {
                    b.HasOne("Bookshelf.DataModel.Book", null)
                        .WithMany()
                        .HasForeignKey("book")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_category_book");

                    b.HasOne("Bookshelf.DataModel.Category", null)
                        .WithMany()
                        .HasForeignKey("category")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_book_category");
                });

            modelBuilder.Entity("Bookshelf.DataModel.Book", b =>
                {
                    b.Navigation("UserBookRelations");
                });

            modelBuilder.Entity("Bookshelf.DataModel.Publisher", b =>
                {
                    b.Navigation("Books");
                });

            modelBuilder.Entity("Bookshelf.DataModel.User", b =>
                {
                    b.Navigation("UserBookRelations");
                });
#pragma warning restore 612, 618
        }
    }
}
