name: Publish Bookshelf

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Lowercase repository owner
        run: |
          echo "OWNER_LC=${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]' >> $GITHUB_ENV

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Publish Api
        run: dotnet publish Bookshelf.Api/Bookshelf.Api.csproj --os linux --arch x64 /t:PublishContainer -c Release /p:ContainerRegistry=${{ env.REGISTRY }} /p:ContainerImageTag=${{ github.ref_name }} /p:ContainerRepository=${{ env.OWNER_LC }}/bookshelf-api

      - name: Publish MigrationService
        run: dotnet publish Bookshelf.MigrationService/Bookshelf.MigrationService.csproj --os linux --arch x64 /t:PublishContainer -c Release /p:ContainerRegistry=${{ env.REGISTRY }} /p:ContainerImageTag=${{ github.ref_name }} /p:ContainerRepository=${{ env.OWNER_LC }}/bookshelf-migration-service

      - name: Build and push Web
        uses: docker/build-push-action@v5
        with:
          context: ./Bookshelf.Web
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.OWNER_LC }}/bookshelf-web:latest
            ${{ env.REGISTRY }}/${{ env.OWNER_LC }}/bookshelf-web:${{ github.ref_name }}